//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecricity_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Counter()
        {
            this.Counter_reading = new HashSet<Counter_reading>();
            this.Perconal_account = new HashSet<Perconal_account>();
        }
    
        public int Id_counter { get; set; }
        public string Mark { get; set; }
        public string Serial_number { get; set; }
        public string Seal_number { get; set; }
        public int Id_tarif { get; set; }
        public string Photo { get; set; }
    
        public virtual Tarif Tarif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Counter_reading> Counter_reading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perconal_account> Perconal_account { get; set; }
    }
}
