//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecricity_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter_reading
    {
        public int Id_indication { get; set; }
        public string Id_personal_account { get; set; }
        public int Id_counter { get; set; }
        public Nullable<System.DateTime> Date_current_indication { get; set; }
        public Nullable<int> Current_indication { get; set; }
        public Nullable<System.DateTime> Date_past_indication { get; set; }
        public Nullable<int> Past_indication { get; set; }
        public Nullable<int> Consumption { get; set; }
        public Nullable<decimal> Value_tarif { get; set; }
        public Nullable<decimal> Accrued { get; set; }
    
        public virtual Counter Counter { get; set; }
        public virtual Perconal_account Perconal_account { get; set; }
    }
}
