//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecricity_billing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<Counter_reading> Counter_reading { get; set; }
        public virtual DbSet<Perconal_account> Perconal_account { get; set; }
        public virtual DbSet<Reading_indication> Reading_indication { get; set; }
        public virtual DbSet<Tarif> Tarif { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
