//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecricity_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perconal_account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perconal_account()
        {
            this.Counter_reading = new HashSet<Counter_reading>();
            this.Reading_indication = new HashSet<Reading_indication>();
        }
    
        public string Id_personal_account { get; set; }
        public string Payer { get; set; }
        public string Number_lot { get; set; }
        public Nullable<decimal> Land_area { get; set; }
        public int Id_counter { get; set; }
    
        public virtual Counter Counter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Counter_reading> Counter_reading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reading_indication> Reading_indication { get; set; }
    }
}
