//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecricity_billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading_indication
    {
        public int Id_payment { get; set; }
        public string Id_personal_account { get; set; }
        public Nullable<decimal> Opening_balance { get; set; }
        public Nullable<decimal> Accrued { get; set; }
        public Nullable<decimal> Total_penalties { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Closing_balance { get; set; }
    
        public virtual Perconal_account Perconal_account { get; set; }
    }
}
